language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
- apt-get -qq update
# Make sure python development tools are installed
- apt-get install -y python3-dev python3-setuptools
# Install GMP
- apt-get install -y libgmp10 libgmp-dev libgmp3c2
# Install PBC
- wget http://voltar.org/pbcfiles/libpbc0_0.5.12_amd64.deb
- wget http://voltar.org/pbcfiles/libpbc-dev_0.5.12_amd64.deb
- dpkg -i libpbc0_0.5.12_amd64.deb
- dpkg -i libpbc-dev_0.5.12_amd64.deb
# Install OpenSSL
- apt-get install -y openssl
# Download charm
- git clone git@github.com:denniss17/charm.git
install:
- pip install -r charm/requirements.txt
- ./charm/configure.sh
- ./charm/make
- ./charm/make install
script:
- nosetests